condense_wildcard_suffixes = true
hard_tabs = true
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
max_width = 180
imports_granularity = "Crate"
newline_style = "Unix"
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
use_try_shorthand = true