name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Build test file
        run: cargo run -q -- run
        working-directory: ./tests/example
